<a href="https://colab.research.google.com/github/ShauryaPrakashVerma/Machine_Learning_Practice/blob/main/17_APIs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import requests

In [ ]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=57686d5405f70dab7d626d8966e891d2&language=en-US&page=1')

In [ ]:
temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [ ]:
temp_df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,302.0875,9.000,1430
1,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,73.8924,8.721,30413
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,47.8459,8.687,22950
3,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,351.8456,8.636,4211
4,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,29.3618,8.571,13911
5,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,30.7355,8.569,17459
6,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,23.1122,8.561,9984
7,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20,35.9329,8.500,18317
8,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,2008-07-16,48.8874,8.531,35778
9,1330021,Remarkably Bright Creatures,Through unlikely bonds formed during night shi...,2026-05-07,87.7660,8.533,456
10,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,19.0353,8.500,4589
11,497,The Green Mile,A supernatural tale set on death row in a Sout...,1999-12-10,31.0256,8.506,19256
12,122,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,2003-12-17,44.5548,8.498,26540
13,1181678,¿Quieres ser mi hijo?,"Lu, a conformist woman in her forties, learns ...",2023-09-21,13.6161,8.497,347
14,496243,Parasite,"All unemployed, Ki-taek's family takes peculia...",2019-05-30,39.0846,8.500,20630
15,680,Pulp Fiction,"A burger-loving hit man, his philosophical par...",1994-09-10,36.8495,8.484,30199
16,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,2016-08-26,29.4314,8.479,12561
17,157336,Interstellar,The adventures of a group of explorers who mak...,2014-11-05,81.0831,8.475,39826
18,429,"The Good, the Bad and the Ugly",While the Civil War rages on between the Union...,1966-12-23,22.9763,8.470,9629
19,13,Forrest Gump,A man with a low IQ has accomplished great thi...,1994-06-23,34.1886,8.465,29747

In [ ]:
df = pd.DataFrame()

In [ ]:
for i in range(1,429):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=57686d5405f70dab7d626d8966e891d2&language=en-US&page={}'.format(i))
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df = pd.concat([df, temp_df], ignore_index=True)

In [ ]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,302.0875,9.000,1430
1,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,73.8924,8.721,30413
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,47.8459,8.687,22950
3,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,351.8456,8.636,4211
4,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,29.3618,8.571,13911
...,...,...,...,...,...,...,...
8555,1290417,Thrash,When a Category 5 hurricane decimates a coasta...,2026-04-10,23.2679,6.024,599
8556,382598,Full Speed,A family together with their grandpa go on a v...,2016-11-11,1.7079,6.024,672
8557,289727,The Rewrite,An Oscar-winning writer in a slump leaves Holl...,2014-06-15,1.9648,6.024,634
8558,64689,Killing Them Softly,Jackie Cogan is an enforcer hired to restore o...,2012-07-30,2.8497,6.025,2404
8559,82,Miami Vice,A case involving drug lords and murder in Sout...,2006-07-27,3.4852,6.000,1957

In [ ]:
df.shape

(8560, 7)

In [ ]:
df.to_csv('movies.csv')