<a href="https://colab.research.google.com/github/ShauryaPrakashVerma/Machine_Learning_Practice/blob/main/28_Column_Transformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df = pd.read_csv('covid_toy.csv')

In [5]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [6]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [7]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [ ]:
# since fever column has null values so it need preprocessing.

In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df.drop(columns = ['has_covid']), df['has_covid'], test_size=0.2)

In [10]:
x_train

    age  gender  fever   cough       city
40   49  Female  102.0    Mild      Delhi
86   25    Male  104.0    Mild  Bangalore
76   80    Male  100.0    Mild  Bangalore
87   47    Male  101.0  Strong  Bangalore
74   34  Female  104.0  Strong      Delhi
..  ...     ...    ...     ...        ...
21   73    Male   98.0    Mild  Bangalore
99   10  Female   98.0  Strong    Kolkata
61   81  Female   98.0  Strong     Mumbai
95   12  Female  104.0    Mild  Bangalore
5    84  Female    NaN    Mild  Bangalore

[80 rows x 5 columns]

In [12]:
# Labour procedure


# adding simple imputer to fever col
# SimpleImputer is a scikit-learn class used to fill in missing values in datasets using simple strategies like mean, median, most frequent, or a constant value.

si = SimpleImputer()
x_train_fever = si.fit_transform(x_train[['fever']])

# also the test data
x_test_fever = si.fit_transform(x_test[['fever']])

x_train_fever.shape

(80, 1)

In [13]:
# Ordinal Encoding --> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
x_train_cough = oe.fit_transform(x_train[['cough']])

# also the test data
x_test_cough = oe.fit_transform(x_test[['cough']])

x_train_cough.shape

(80, 1)

In [29]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop='first', sparse_output=False)
x_train_gender_city = ohe.fit_transform(x_train[['gender','city']])

# also the test data
x_test_gender_city = ohe.fit_transform(x_test[['gender','city']])

x_train_gender_city.shape

(80, 4)

In [30]:
# Extracting Age
x_train_age = x_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
x_test_age = x_test.drop(columns=['gender','fever','cough','city']).values

x_train_age.shape

(80, 1)

In [31]:
x_train_transformed = np.concatenate((x_train_age,x_train_fever,x_train_gender_city,x_train_cough),axis=1)
# also the test data
x_test_transformed = np.concatenate((x_test_age,x_test_fever,x_test_gender_city,x_test_cough),axis=1)

x_train_transformed.shape

(80, 7)



---

In [32]:
# smart method
from sklearn.compose import ColumnTransformer

In [33]:
transformer = ColumnTransformer(transformers=[('tnf1', SimpleImputer(), ['fever']), ('tnf2', OrdinalEncoder(categories=[['Mild', 'Strong']]), ['cough']), ('tnf3', OneHotEncoder(sparse_output=False, drop='first'), ['gender', 'city'])], remainder='passthrough')

In [34]:
transformer.fit_transform(x_train).shape

(80, 7)

In [35]:
transformer.transform(x_test).shape

(20, 7)